//
//  HydraulicCylinderForceCalculator.swift
//  EngineeringToolbox
//
//  Created by ali cihan on 10.09.2026.
//

/// Calculates the extension force generated by pressure acting on a hydraulic
/// cylinder bore. Inputs use bar and millimetres; the reported force is kN.
struct HydraulicCylinderForceCalculator: EngineeringCalculator {
    let id = "hydraulic-cylinder-force"
    let title = "Hydraulic Cylinder Force"
    let category: CalculatorCategory = .fluidThermal
    let mode: CalculatorMode = .fixedOutput(outputKey: "force")

    let fields: [CalculatorField] = [
        CalculatorField(key: "pressure", label: "Pressure", unit: "bar"),
        CalculatorField(key: "bore", label: "Bore Diameter", unit: "mm"),
        CalculatorField(key: "force", label: "Push Force", unit: "kN")
    ]

    func compute(known: [String: Double], solveFor: String) -> Double? {
        guard solveFor == "force",
              let pressureBar = known["pressure"],
              let boreMillimetres = known["bore"],
              pressureBar.isFinite,
              boreMillimetres.isFinite,
              pressureBar >= 0,
              boreMillimetres > 0
        else {
            return nil
        }

        let pressurePascals = pressureBar * 100_000
        let boreMetres = boreMillimetres / 1_000
        let radiusMetres = boreMetres / 2
        let areaSquareMetres = Double.pi * radiusMetres * radiusMetres
        let forceKilonewtons = (pressurePascals * areaSquareMetres) / 1_000

        return forceKilonewtons.isFinite ? forceKilonewtons : nil
    }
}
